import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import os
import markdown

class Mailer:
    def __init__(self, config=None):
        self.config = config or {}
        self.sender = self.config.get("EMAIL_SENDER") or os.environ.get("EMAIL_SENDER")
        self.password = self.config.get("EMAIL_PASSWORD") or os.environ.get("EMAIL_PASSWORD")
        self.receivers = self.config.get("EMAIL_RECEIVER") or os.environ.get("EMAIL_RECEIVER")
    
    def send_detailed_plan(self, plan_dict):
        if not self.sender or not self.password:
            print("Email credentials not set. Skipping email.")
            return

        # Check if plan_dict has 'days' (new detailed format)
        if 'days' not in plan_dict:
            # Fallback for legacy
            self.send_plan(plan_dict.get('summary_message', 'Meal Plan'))
            return

        # Construct Rich HTML Email
        html_content = f"""
        <html>
        <head>
            <style>
                body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f9fafb; padding: 20px; }}
                .container {{ max_width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
                .header {{ background: #4f46e5; color: white; padding: 30px 20px; text-align: center; }}
                .header h1 {{ margin: 0; font-size: 24px; }}
                .summary {{ padding: 20px; background: #eef2ff; color: #3730a3; font-style: italic; border-bottom: 1px solid #e5e7eb; }}
                .day-card {{ padding: 20px; border-bottom: 1px solid #f3f4f6; }}
                .day-title {{ font-size: 18px; font-weight: bold; color: #111827; margin-bottom: 15px; text-transform: uppercase; letter-spacing: 0.05em; }}
                .meal-block {{ margin-bottom: 20px; padding-left: 15px; border-left: 4px solid #e5e7eb; }}
                .meal-type {{ font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 5px; display: block; }}
                .meal-name {{ font-size: 16px; font-weight: bold; color: #1f2937; margin: 0 0 10px 0; }}
                .recipe-details {{ font-size: 14px; color: #4b5563; background: #f9fafb; padding: 10px; border-radius: 8px; }}
                .section-title {{ font-size: 12px; font-weight: bold; text-transform: uppercase; color: #9ca3af; margin-top: 10px; margin-bottom: 5px; }}
                .shopping-list {{ padding: 30px 20px; background: #f8fafc; }}
                .footer {{ text-align: center; font-size: 12px; color: #9ca3af; padding: 20px; }}
                
                .text-orange {{ color: #f97316; border-color: #f97316; }}
                .text-green {{ color: #10b981; border-color: #10b981; }}
                .text-blue {{ color: #6366f1; border-color: #6366f1; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Weekly Meal Plan</h1>
                </div>
                
                <div class="summary">
                    "{plan_dict['summary_message']}"
                </div>
                
                <!-- Days -->
                {''.join([self._render_day_email(day) for day in plan_dict['days']])}
                
                <!-- Shopping List -->
                <div class="shopping-list">
                    <h2 style="margin-top:0; color: #1e293b;">Shopping List</h2>
                    <ul style="padding-left: 20px; color: #475569;">
                        {''.join([f'<li>{item}</li>' for item in plan_dict['shopping_list']])}
                    </ul>
                </div>
                
                <div class="footer">
                    Generated by Arby
                </div>
            </div>
        </body>
        </html>
        """

        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"Arby Menu: {datetime.now().strftime('%b %d')} - Recipes Included"
        msg['From'] = self.sender
        
        # Handle multiple receivers
        receiver_list = [r.strip() for r in self.receivers.split(',')] if self.receivers else []
        msg['To'] = ", ".join(receiver_list)

        part2 = MIMEText(html_content, 'html')
        msg.attach(part2)

        try:
            with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp_server:
                smtp_server.login(self.sender, self.password)
                smtp_server.sendmail(self.sender, receiver_list, msg.as_string())
            print("Detailed Email sent successfully!")
        except Exception as e:
            print(f"Failed to send email: {e}")

    def _render_day_email(self, day):
        # Helper to render a single day's HTML
        html = f'<div class="day-card"><div class="day-title">{day["date"]}</div>'
        
        for m_type, color in [("breakfast", "text-orange"), ("lunch", "text-green"), ("dinner", "text-blue")]:
            meal = day.get(m_type)
            if meal:
                html += f"""
                <div class="meal-block" style="border-left-color: {'#f97316' if m_type=='breakfast' else '#10b981' if m_type=='lunch' else '#6366f1'};">
                    <span class="meal-type {color}">{m_type}</span>
                    <h3 class="meal-name">{meal.get('name')}</h3>
                    <div class="recipe-details">
                        <div class="section-title">Ingredients</div>
                        <ul style="margin: 0; padding-left: 15px; margin-bottom: 10px;">
                            {''.join([f'<li>{i}</li>' for i in meal.get('ingredients', [])])}
                        </ul>
                        <div class="section-title">Instructions</div>
                        <ol style="margin: 0; padding-left: 15px;">
                            {''.join([f'<li>{s}</li>' for s in meal.get('instructions', [])])}
                        </ol>
                    </div>
                </div>
                """
        html += '</div>'
        return html
